server:
  port: 8761

spring:
  application:
     name: ead-service-registry

eureka:
  client:
    registerWithEureka: false #Não vai se cadastrar como um cliente e sim como um servidor
    fetchRegistry: false #não vai buscar um registro no Eureka