server:
  port: 8761

spring:
  application:
     name: ead-service-registry

ead:
  serviceRegistry:
    username: serviceregistry
    password: 'ead123'

eureka:
  client:
    registerWithEureka: false #Não vai se cadastrar como um cliente e sim como um servidor
    fetchRegistry: false #não vai buscar um registro no Eureka
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'