server:
  port: 8080

spring:
  application:
    name: ead-api-gateway
  #definição das rotas de cada microservice
  cloud:
    gateway:
      routes:
        - id: authuser-service
          uri: http://localhost:8082/
          predicates:
            - Path=/ead-authuser/**

        - id: course-service
          uri: http://localhost:8083/
          predicates:
            - Path=/ead-course/**
