server:
  port: 8083
  servlet:
    context-path: '/ead-course/'

spring:
  application:
    name: ead-course-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  jmx:
    enabled: false
  datasource:
    username: postgres
    password: T@ider1398
    url: jdbc:postgresql://localhost:5432/ead-course-v2
#RabbitMQ configuração
  rabbitmq:
    addresses: amqps://ukutjcsw:9PA1G6yANv6SylwjCluGIFpO2ylCaEEF@fly.rmq.cloudamqp.com/ukutjcsw

#definição do endereço de AuthUser para comunicação síncrona entre os microserviços
ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser-v2' #passei o ID do Eureka e o context-path

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost