server:
  port: 8888 #porta default para clientConfigServer

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BrunoGago/ead-config-server-repo
          default-label: main #branch

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
    instance:
      hostname: localhost


